# -*- coding: utf-8 -*-
"""fitbuddy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVYzQwXInPJtpkwyRD5lOmRVqqjNfqze
"""

!pip install mediapipe==0.10.5 --upgrade --force-reinstall

from google.colab import files
import zipfile
import os

# ZIP 파일 수동 업로드
uploaded = files.upload()

# 압축 해제 (업로드한 zip파일명 예: posture_images.zip)
for fname in uploaded.keys():
    with zipfile.ZipFile(fname, 'r') as zip_ref:
        zip_ref.extractall("/content/posture_images")

import mediapipe as mp
mp_pose = mp.solutions.pose
pose = mp_pose.Pose(static_image_mode=True)
print("✅ MediaPipe Pose 로딩 성공")

import glob

base_dir = "/content/posture_images"
image_paths = sorted(glob.glob(os.path.join(base_dir, "**", "*.jpg"), recursive=True))
print(f"총 이미지 개수: {len(image_paths)}")

import mediapipe as mp
import cv2
import pandas as pd
from tqdm import tqdm

# pose 모델
mp_pose = mp.solutions.pose
pose = mp_pose.Pose(static_image_mode=True)

def extract_pose_keypoints(image_path):
    image = cv2.imread(image_path)
    if image is None:
        print(f"이미지 로드 실패: {image_path}")
        return None
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = pose.process(image_rgb)
    if not results.pose_landmarks:
        return None
    keypoints = []
    for lm in results.pose_landmarks.landmark:
        keypoints.append(lm.x)
        keypoints.append(lm.y)
    return keypoints

# 전체 데이터 수집
X = []
y = []

for path in tqdm(image_paths):
    label = os.path.basename(os.path.dirname(path))  # 폴더 이름 = 자세 이름
    keypoints = extract_pose_keypoints(path)
    if keypoints is not None:
        X.append(keypoints)
        y.append(label)

df = pd.DataFrame(X)
df['label'] = y

print(df.head())

import os
import pandas as pd
from tqdm import tqdm

keypoint_list = []
filename_list = []

# 이미지 없을 경우 예외 처리
if not image_paths:
    print("⚠️ 이미지 경로가 비어있어요!")
else:
    for path in tqdm(image_paths):
        keypoints = extract_pose_keypoints(path)
        if keypoints is not None:
            keypoint_list.append(keypoints)
            filename_list.append(os.path.basename(path))  # 파일명만 저장
        else:
            print(f"❌ 포즈 추출 실패: {path}")

import pandas as pd

# keypoints → DataFrame
df = pd.DataFrame(keypoint_list)

# 열 이름 지정 (0~65 → x1, y1, x2, y2, ..., x33, y33)
df.columns = [f'kp_{i}' for i in range(66)]

# 파일명 추가
df['filename'] = filename_list

# 결과 확인
print(f"✅ DataFrame 크기: {df.shape}")  # (n, 67)
df.head()

import pickle

# 저장 경로 (Colab 내부 경로)
save_path = "/content/pose_keypoints.pkl"

# 피클 저장
with open(save_path, "wb") as f:
    pickle.dump(df, f)

print(f"✅ 피클 저장 완료: {save_path}")

import pandas as pd
import numpy as np
import pickle

# 1. 기존 키포인트 CSV 로드 (이제는 Colab 내부 경로 사용 가정)
df = pd.read_csv("/content/pose_keypoints.csv")

# 2. 자동 라벨링 함수
def auto_label_from_pose(keypoints):
    x = keypoints[::2]
    y = keypoints[1::2]

    # MediaPipe index 기준
    LS, LE, LW = 11, 13, 15   # Left Shoulder, Elbow, Wrist
    LH, LK, LA = 23, 25, 27   # Left Hip, Knee, Ankle

    # 조건 1: 팔꿈치가 어깨보다 안쪽에 위치하지 않음 (수직 정렬)
    cond1 = abs(x[LS] - x[LE]) < 0.15

    # 조건 2: 어깨-엉덩이-발목 y 좌표 정렬 유지 (일직선)
    y_std = np.std([y[LS], y[LH], y[LA]])
    cond2 = y_std < 0.03

    # 조건 3: 상체가 바닥에서 너무 낮지 않음 (어깨와 팔꿈치 y차이 확보)
    cond3 = (y[LE] - y[LS]) > 0.03

    return int(cond1 and cond2 and cond3)

# 3. keypoints 리스트 생성 후 라벨링 적용
df["keypoints"] = df.iloc[:, :66].values.tolist()
df["label"] = df["keypoints"].apply(auto_label_from_pose)
df.drop(columns=["keypoints"], inplace=True)

# 4. 피클로 저장
save_path = "/content/pose_keypoints_with_labels.pkl"
with open(save_path, "wb") as f:
    pickle.dump(df, f)

print(f"✅ 라벨링 완료 및 피클 저장: {save_path}")

"""지혜가 해야할 것

1. 데이터셋 구성
모든 이미지의 keypoints를 뽑고 그 이미지가 어떤 자세인지(label: 예를 들어 plank=0, squat=1 등) 연결해서 X (keypoints), y (label) 데이터셋 만들기

2. 모델 학습
간단한 모델 예시: RandomForestClassifier 또는 KNN, MLPClassifier 학습 후 accuracy 확인

3. 모델 평가
예측 정확도, confusion matrix 등
"""

# 1. 모든 이미지에서 keypoints 추출 & 라벨링

import pandas as pd

# 폴더명(=자세명)을 라벨로 사용
from tqdm import tqdm

X = []  # keypoints
y = []  # label

for path in tqdm(image_paths):
    label = os.path.basename(os.path.dirname(path))  # 폴더명이 라벨
    keypoints = extract_pose_keypoints(path)
    if keypoints is not None:
        X.append(keypoints)
        y.append(label)

# DataFrame으로 변환
df = pd.DataFrame(X)
df['label'] = y

print(f"총 데이터 수: {len(df)}")
df.head()

# 2. 문자열 라벨 → 숫자 인코딩 + 훈련/테스트 분리

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# 라벨 인코딩 (ex. plank -> 0, squat -> 1)
le = LabelEncoder()
df['label'] = le.fit_transform(df['label'])

# 특징(X)과 타겟(y) 분리
X = df.drop(columns='label')
y = df['label']

# train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"훈련: {len(X_train)}개, 테스트: {len(X_test)}개")
print("클래스 인코딩:", dict(zip(le.classes_, le.transform(le.classes_))))

# 3. 모델 학습 (Random Forest)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("모델 학습 완료!")

# 4. 모델 평가

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# 예측
y_pred = model.predict(X_test)

# 정확도
acc = accuracy_score(y_test, y_pred)
print(f"정확도: {acc * 100:.2f}%")

# 상세 리포트
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=le.classes_, yticklabels=le.classes_, cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()
